services:
  - icon: fa-cutlery
    link: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt
    title: Catering
  - icon: fa-bullhorn
    link: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt
    title: Conference Services
  - icon: fa-plus
    link: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt
    title: Room Setup
  - icon: fa-music
    link: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt
    title: Audio/Visuals
  - icon: fa-print
    link: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt
    title: Printing
  - icon: fa-wifi
    link: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt
    title: WiFi
  - icon: fa-map-signs
    link: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt
    title: Floor Planning
  - icon: fa-car
    link: >-
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
      tempor incididunt
    title: Parking
